Shuru Krte Hai
    maan le a = 10;
    maan le b = 15;
    a = a + 1;
    likh bey "Value of a:", a;
    bhai agar (a < 20) {
        likh bey "a is less than 20";
    } nahi to bhai (a < 25) {
        likh bey "a is less than 25";
    } warna last option {
        likh bey "a is 25 or more";
    }
    jab tak (a < 15) {
        a += 1;
        likh bey a;
        bhai agar (a == 13) {
            bahar nikal ja;
        }
    }
Ab Thak gaya